### ISSUE TITLE
Support association's :class_name option set to a constant

### ISSUE THREAD

**Issue by franzliedke** [k0kubun/activerecord-precount#18]
When defining a relationship with the `class_name:` option set to a class constant (e.g. `Article` instead of `'Article'`), I get the following error when using this addon:

    NoMethodError: undefined method `match' for #<Class:0x000000049233e0>

**Comment by k0kubun** [comment]
Sorry for unkind error message but you should use class option for that use case.

**Comment by franzliedke** [comment]
Huh? It works when I use `Article` as a string, but it doesn't when I use `Article` as a class constant.

I've been looking into it and it seems like a little bit of `to_s` [here](https://github.com/k0kubun/activerecord-precount/blob/91e5812d26c462dee84a7a6db3b8ffad46f94d14/lib/active_record/precount/reflection_extension.rb#L27) should solve the issue?

**Comment by k0kubun** [comment]
I've thought :class_name is for String and :class is for Class.

That fix is acceptable.

**Comment by franzliedke** [comment]
Never mind. Apparently [we're not supposed to use constants here](http://stackoverflow.com/questions/20390991/activerecord-pass-class-instead-of-string-to-class-name-when-defining-associati).
