### ISSUE TITLE
fatal (exception reentered):

### ISSUE THREAD

**Issue by kntmrkm** [k0kubun/activerecord-precount#22]
I got error `fatal (exception reentered):` with `bullet` and `search_cop` gem.

I don't know these gem related to error.

But, I was able to reproduce by simple project.
https://github.com/kntmrkm/search_cop_with_bullet

```
bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rake db:seed
```

and, in `rails console`, execute below command.

`User.take.comments.search_by_q('n')`

Command will not finished.
On the view process. You will get `fatal (exception reentered):` error. 
(above repo does not include view process)

After remove `activerecord-precount`.
The error will disappears.

thanks.

**Comment by kntmrkm** [comment]
Additional info.
If remove `bullet` gem.
The error does not occurs.

**Comment by k0kubun** [comment]
@kntmrkm Could you try this? https://github.com/flyerhzm/bullet/pull/330
cc/ @kenchan0130

**Comment by kntmrkm** [comment]
This is current problem.

<img width="1014" alt="action_controller__exception_caught" src="https://cloud.githubusercontent.com/assets/2703486/24575827/5d8083e0-16eb-11e7-9183-2736f445545f.png">

With `gem 'bullet', github: 'k0kubun/bullet', branch: 'module-prepend'`.

**Solved**

----

ちなみに、ruby2.4.1だと以下のようなエラーになりました。
問題のエラーは解消されました。ありがとうございます。

<img width="1199" alt="1__fsevent_watch" src="https://cloud.githubusercontent.com/assets/2703486/24575881/5a9e6cb8-16ec-11e7-8641-9712e1066adf.png">

**Comment by k0kubun** [comment]
Closing because https://github.com/flyerhzm/bullet/pull/330 is merged.

<hr>

The second error may be bug for combination of Ruby 2.4.1 and ActiveSupport or in GC.
