### ISSUE TITLE
Rails 5.1 ActionView::Template::Error: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by ysdanielkim** [k0kubun/activerecord-precount#24]
After upgrading to Rails 5.1, I'm getting the following error originating from `preloader_extension.rb:49`
```
ActionView::Template::Error: undefined method `map' for nil:NilClass
```

Adding the following to line 49 seems to do the trick but I'm not sure what is causing this behavior.
```
return {} if @preloaded_records.empty?
```

Does anyone have any insight on why this might be happening? Below is the full stack trace

```
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-precount-0.6.3/lib/active_record/precount/preloader_extension.rb:50:in `load_records'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader/association.rb:61:in `associated_records_by_owner'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-precount-0.6.3/lib/active_record/precount/preloader_extension.rb:21:in `preload'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader/association.rb:19:in `run'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader.rb:151:in `block (2 levels) in preloaders_for_one'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader.rb:149:in `each'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader.rb:149:in `map'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader.rb:149:in `block in preloaders_for_one'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader.rb:148:in `each'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader.rb:148:in `flat_map'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader.rb:148:in `preloaders_for_one'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader.rb:115:in `preloaders_on'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader.rb:102:in `block in preload'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader.rb:101:in `each'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader.rb:101:in `flat_map'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/associations/preloader.rb:101:in `preload'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/relation.rb:667:in `block in exec_queries'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/relation.rb:665:in `each'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/relation.rb:665:in `exec_queries'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/relation.rb:547:in `load'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/relation.rb:255:in `records'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/relation.rb:251:in `to_a'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/will_paginate-3.1.5/lib/will_paginate/active_record.rb:126:in `block in to_a'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/will_paginate-3.1.5/lib/will_paginate/collection.rb:96:in `create'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/will_paginate-3.1.5/lib/will_paginate/active_record.rb:125:in `to_a'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/relation/finder_methods.rb:524:in `find_take_with_limit'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/relation/finder_methods.rb:100:in `take'"
"/Users/youkib/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0/lib/active_record/relation.rb:639:in `inspect'"
...
```

Thanks in advance for any assistance and I'd be more than happy to make a pull request if this is the correct fix to the problem.

**Comment by k0kubun** [comment]
I'm not sure what's the correct fix. But surely your PR would be appreciated if all tests pass.

The current maintenance policy is [this](https://github.com/k0kubun/activerecord-precount/pull/23#issuecomment-281215186). I'll add anyone who can fix new issues to repository collaborators and gem owners.

**Comment by naoki-k** [comment]
I have encountered same error and succeeded to fix this problem, but I'm not sure my approach is appropiate too and still can't send pull request.

In ActiveRecord5.1 with activerecord-precount, there are two problems.

Firstly, `ActiveRecord::Associations::CollectionAssociation#count` has removed in AR 5.1, but activerecord-precount uses this method. (ref: https://github.com/rails/rails/pull/26383)
In my approach, simply extending the above method defined as extension.

Secondly, I cannot specified the cause of root not yet. Howerver, I have confirmed that it existes the difference of return type of `records_for` method between using AR __5.0,2__ and AR __5.1__ .
I have succeeded to pass all test by transforming the return value of `records_for` to the appropriate type against this problem, but I think this is not the fundamental solution.

I hope this will help.

**Comment by kenju** [comment]
@ysdanielkim 

I have faced with the same problem, and fixed with https://github.com/k0kubun/activerecord-precount/pull/25 . Please retry after this patch is released.

@naoki-k 

Thanks for your insightful comment. Though the deletion of `ActiveRecord::Associations::CollectionAssociation#count` is not this issues's root cause, this may

Have a look at [the current CI with Rails v5.1.x build](https://travis-ci.org/k0kubun/activerecord-precount/jobs/245641217), 

```rb

**Comment by kenju** [comment]
FYI @naoki-k 

> Howerver, I have confirmed that it existes the difference of return type of records_for method between using AR 5.0.2 and AR 5.1 .

This is because the `records_for` was removed at https://github.com/rails/rails/pull/26379

**Comment by kenju** [comment]
FYI @naoki-k 
`NoMethodError: undefined method `count'` error was resolved at https://github.com/k0kubun/activerecord-precount/pull/27 , and your inspection was great helpful. Thanks!
